site_name: Express Acl
repo_url: https://github.com/andela-thomas/express-acl
site_description: This is documentation for express-acl project
site_favicon: favicon.ico
strict: true
# css  and javascript

extra_css: [css/extra.css]
extra_javascript:
#
pages:
  - Home: index.md
  - Documentation:
      - Getting started: documentation/getting-started.md
      - Configuration options: documentation/configuration.md
      - Api Methods: documentation/methods.md
      - Acl Rules: documentation/rules.md
      - Status Codes and Responses: documentation/status-and-responses.md
  - Contribution: contribution.md
theme: material
markdown_extensions:
  - codehilite
  - admonition
